using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace Choropleth_Map
{
    public class ViewModel
    {
        public ObservableCollection<CountryDensityModel> WorldPopulationDensityDetails { get; set; }
        public ViewModel()
        {
            WorldPopulationDensityDetails = new ObservableCollection<CountryDensityModel>();
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Taiwan", 672));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bangladesh", 1265));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Israel", 400));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tuvalu", 393));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Belgium", 382));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Curacao", 369));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Philippines", 367));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sint Maarten", 1261));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bermuda", 1246));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Channel Islands", 915));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("State of Palestine", 847));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint-Martin", 729));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mayotte", 727));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Barbados", 668));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Lebanon", 667));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mauritius", 626));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Aruba", 593));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("San Marino", 565));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Nauru", 541));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Korea", 527));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Rwanda", 525));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Netherlands", 508));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Comoros", 467));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("India", 464));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Burundi", 463));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint-Barthélemy", 449));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Haiti", 413));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Reunion", 358));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Martinique", 354));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Japan", 346));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sri Lanka", 341));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Grenada", 331));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Marshall Islands", 328));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Puerto Rico", 322));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Vietnam", 313));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("El Salvador", 313));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guam", 312));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint Lucia", 301));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("United States Virgin Islands", 298));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Pakistan", 286));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint Vincent and the Grenadines", 284));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("United Kingdom", 280));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("American Samoa", 276));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cayman Islands", 273));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Jamaica", 273));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Trinidad and Tobago", 272));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Qatar", 248));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guadeloupe", 245));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Luxembourg", 241));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Germany", 240));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kuwait", 239));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Gambia", 238));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Liechtenstein", 238));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Uganda", 228));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sao Tome and Principe", 228));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Nigeria", 226));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Dominican Rep.", 224));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Antigua and Barbuda", 222));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Switzerland", 219));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Dem. Rep. Korea", 214));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Seychelles", 213));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Italy", 205));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint Kitts and Nevis", 204));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Nepal", 203));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Malawi", 202));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("British Virgin Islands", 201));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guatemala", 167));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Anguilla", 166));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Andorra", 164));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Micronesia", 164));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("China", 153));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Togo", 152));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Indonesia", 151));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Isle of Man", 149));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kiribati", 147));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tonga", 146));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Czech Rep.", 138));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cabo Verde", 138));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Thailand", 136));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ghana", 136));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Denmark", 136));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tokelau", 135));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cyprus", 130));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Northern Mariana Islands", 125));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Poland", 123));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Moldova", 122));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Azerbaijan", 122));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("France", 119));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("United Arab Emirates", 118));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ethiopia", 115));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Jordan", 114));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Slovakia", 113));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Portugal", 111));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sierra Leone", 110));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Turkey", 109));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Austria", 109));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Benin", 107));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Hungary", 106));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cuba", 106));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Albania", 105));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Armenia", 104));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Slovenia", 103));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Egypt", 102));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Serbia", 99));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Costa Rica", 99));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Malaysia", 98));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Dominica", 95));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Syria", 95));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cambodia", 94));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kenya", 94));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Spain", 93));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Iraq", 92));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Timor-Leste", 88));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Honduras", 88));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Senegal", 86));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Romania", 83));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Myanmar", 83));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Brunei Darussalam", 83));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ivory Coast", 82));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Morocco", 82));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Macedonia", 82));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Greece", 80)); 
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kosovo", 164));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Wallis and Futuna Islands", 80));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bonaire, Sint Eustatius and Saba", 79));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Uzbekistan", 78));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("French Polynesia", 76));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Burkina Faso", 76));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tunisia", 76));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ukraine", 75));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Croatia", 73));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cook Islands", 73));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ireland", 71));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Ecuador", 71));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Lesotho", 70));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Samoa", 70));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guinea-Bissau", 69));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tajikistan", 68));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Eswatini", 67));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Tanzania", 67));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mexico", 66));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bosnia and Herz.", 64));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bulgaria", 64));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Afghanistan", 59));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Panama", 58));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Georgia", 57));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Yemen", 56));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Cameroon", 56));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Nicaragua", 55));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guinea", 53));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Liberia", 52));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Iran", 51));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Eq. Guinea", 50));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Montserrat", 49));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Fiji", 49));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("South Africa", 48));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Madagascar", 47));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Montenegro", 46));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Belarus", 46));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Colombia", 45));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Lithuania", 43));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Djibouti", 42));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Turks and Caicos Islands", 40));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mozambique", 39));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Dem. Rep. Congo", 39));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Palau", 39));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bahamas", 39));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Zimbabwe", 38));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("United States of America", 36));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Eritrea", 35));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Faroe Islands", 35));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kyrgyzstan", 34));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Venezuela", 32));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Lao PDR", 31));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Estonia", 31));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Latvia", 30));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Angola", 26));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Peru", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Chile", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Brazil", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Brazil", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Somaliland", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Somalia", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Vanuatu", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint Pierre and Miquelon", 25));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sudan", 24));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Zambia", 24));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Sweden", 24));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Solomon Islands", 24));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bhutan", 20));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Uruguay", 19));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Papua New Guinea", 19));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Niger", 19));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Algeria", 18));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("S. Sudan", 18));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("New Zealand", 18));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Finland", 18));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Paraguay", 17));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Belize", 17));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mali", 16));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Argentina", 16));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Oman", 16));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saudi Arabia", 16));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Congo", 16));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("New Caledonia", 15));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Saint Helena", 15));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Norway", 14));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Chad", 13));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Turkmenistan", 12));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Bolivia", 10));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Russia", 8));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Gabon", 8));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Central African Rep.", 7));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Kazakhstan", 6));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Niue", 6));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mauritania", 4));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Canada", 4));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Botswana", 4));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Guyana", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Libya", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Suriname", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("French Guiana", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Iceland", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Australia", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Namibia", 3));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("W. Sahara", 2));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Mongolia", 2));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Falkland Is.", 0.2));
            WorldPopulationDensityDetails.Add(new CountryDensityModel("Greenland", 0.1));
        }
    }
    public class CountryDensityModel
    {
        public CountryDensityModel(string countryName, double density)
        {
            this.CountryName = countryName;
            this.Density = density;
        }

        public string CountryName { get; set; }
        public double Density { get; set; }
    }

}
